### ISSUE TITLE
ETCD becomes unavailable on update

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/cluster-api-provider-rke2#449]
See https://gitlab.com/sylva-projects/sylva-core/-/issues/1687 for all details describing the issue

**Comment by tmmorin** [comment]
thanks for opening this issue

one precision: the symptom is less clear that "etcd isn't available"... what we clearly see is some controllers failing to get leases from the apiServer, but some controller apparently still can, and we aren't sure that reading from the api is an issue

there are "bad certificates" issues in etcd logs, but they possibly are harmless (they relate to a node which isn't anymore an etcd cluster member)

so at this point we aren't really sure what the best issue title is ... ;-)

**Comment by tmmorin** [comment]
here are two dumps of CI jobs that exhibited the issue:
* https://gitlab.com/sylva-projects/sylva-core/-/jobs/7951588127/artifacts/download (on capo)
* https://gitlab.com/-/project/42451983/uploads/b173fc74cea9cf2d9596e8bb55bd3aff/artifact-7915786264.zip (on capm3)

The relevant info is in management-cluster-dump directory, it has the usual per-ns kubectl cluster-info dumps with pod logs, but also resource dumps for many CRDs, it also has a "clusterctl-describe.txt" which is convenient to see what was CAPI state.

**Comment by tmmorin** [comment]
To have ideas on whether or not our suspicion that https://github.com/rancher/cluster-api-provider-rke2/pull/404 could be contributing to this issue, since yesterday I've ran our CI pipelines with this commit reverted.   In the dozen runs that I did with this commit reverted, I could not reproduce this issue a single time.

This is no proof though, of course, but may help root cause the problem.

We suspected this commit to be a possible cause base on this plausible story line:
- (errors in our pipelines related to etcd certificates - `bad certificate`)
- the fact that we upgrade from a starting point not having the cluster-etcd secret
- ... to a setup where the RKE2 bootstrap provider adds the working kubectl that creates the cluster-etcd secret
- the fact that issue arise right after the creation of the secret (rebuild of the first node with the newer RKE2 bootstrap provider)
We're thinking that we're possibly in a state where the upgrade path designed in https://github.com/rancher/cluster-api-provider-rke2/pull/265 would have some defect.

**Comment by Danil-Grigorev** [comment]
Implementation of the certificate synchronization in the form of pulling the cert to a secret during node bootstrap is a mechanism to ensure that pre-beta clusters provisioned by RKE2 entirely still will function normally, as we moved to `kubeadm` approach with providing a set of certificates for the cluster `etcd` to use, provided from the management cluster.

It seems there is now a third state, when secret is synchronized after upgrade from previous version to the latest, while it was intended that the secret with certificates exist in advance, during the initial cluster bootstrap (created by it).

**Comment by tmmorin** [comment]
> It seems there is now a third state, when secret is synchronized after upgrade from previous version to the latest, while it was intended that the secret with certificates exist in advance, during the initial cluster bootstrap (created by it).

This makes sense. It was also our intuition that the ineffective kubectl command in this initial implementation had "broken" what was the intended upgrade path.
